sonar.projectKey=kharmaodo_gestion-location
sonar.sources=backend/src/main,frontend-web/src
sonar.tests=backend/src/test
sonar.java.binaries=backend/target/classes
sonar.exclusions=**/node_modules/**,**/dist/**,**/target/**
